addSbtPlugin("org.scalameta"      % "sbt-scalafmt"  % "2.5.5")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"  % "2.3.1")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"   % "0.6.4")
addSbtPlugin("se.marcuslonnberg"  % "sbt-docker"    % "1.11.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo" % "0.13.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.8")
