# Indexer StatefulSet for distributed Nixiesearch
# Handles document indexing and uploads to S3
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nixiesearch-indexer
  labels:
    app: nixiesearch
    component: indexer
spec:
  # Single replica for indexing
  replicas: 1
  serviceName: nixiesearch-indexer
  selector:
    matchLabels:
      app: nixiesearch
      component: indexer
  template:
    metadata:
      labels:
        app: nixiesearch
        component: indexer
    spec:
      containers:
      - name: indexer
        # Use the latest Nixiesearch image
        image: nixiesearch/nixiesearch:latest
        imagePullPolicy: Always
        
        # Arguments to run in index mode
        args: [
          "index",
          "--config", "/config/config.yml"
        ]
        
        # Container ports
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        
        # Mount the config file from ConfigMap
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        
        # Resource limits and requests
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Environment variables for AWS credentials
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-access-key
              optional: true
        - name: AWS_REGION
          value: "us-east-1"
      
      # Volume definition for config
      volumes:
      - name: config-volume
        configMap:
          name: nixiesearch-config
      
      # Restart policy
      restartPolicy: Always