# Searcher deployment for distributed Nixiesearch
# Handles search queries using indexes synchronized from S3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nixiesearch-searcher
  labels:
    app: nixiesearch
    component: searcher
spec:
  # Multiple replicas for high availability
  replicas: 2
  selector:
    matchLabels:
      app: nixiesearch
      component: searcher
  template:
    metadata:
      labels:
        app: nixiesearch
        component: searcher
    spec:
      containers:
      - name: searcher
        # Use the latest Nixiesearch image
        image: nixiesearch/nixiesearch:latest
        imagePullPolicy: Always
        
        # Arguments to run in search mode
        args: [
          "search",
          "--config", "/config/config.yml"
        ]
        
        # Container ports
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        
        # Mount the config file from ConfigMap
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        
        # Resource limits and requests
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Environment variables for AWS credentials
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-access-key
              optional: true
        - name: AWS_REGION
          value: "us-east-1"
      
      # Volume definition for config
      volumes:
      - name: config-volume
        configMap:
          name: nixiesearch-config
      
      # Restart policy
      restartPolicy: Always