# Project information
site_name: Nixiesearch
site_url: https://nixiesearch.ai
site_description: >-
  Nixiesearch is an open-source hybrid search engine, which can fine-tune to your documents.

# Repository
repo_url: https://github.com/nixiesearch/nixiesearch
repo_name: nixiesearch/nixiesearch
edit_uri: edit/master/docs/

#Copyright
copyright: © 2024 nixiesearch

# Configuration
theme:
  name: material
  #custom_dir: docs/overrides
  #logo: assets/images/logo.svg
  #favicon: assets/images/dstack-fav-32.ico
  icon:
#    repo: custom/github
    edit: material/pencil
#  font:
#    text: Source Sans Pro
#    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  features:
    #    - navigation.path
    - content.code.copy
    - content.action.edit
    #    - navigation.indexes
    - navigation.tabs
    #    - navigation.instant
    #    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - announce.dismiss
    - navigation.tracking
    - navigation.footer

# Plugins
plugins:
#  - blog:
#      blog_dir: blog
#      blog_toc: true
  - social:
      cards_layout_options:
        background_color: "black"
        color: "#FFFFFF"
        font_family: Roboto
  - search
#  - typeset

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 3
      permalink: true
  - md_in_html
  - footnotes
  - tables

# Customization
#extra_css:
#  - assets/stylesheets/extra.css
#  - assets/stylesheets/termynal.css
#  - assets/stylesheets/landing.css
#extra_javascript:
#  - assets/javascripts/extra.js
extra:
  homepage: /
  generator: false
  analytics:
    provider: google
    property: G-TFXLVGMHME
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/nixiesearch/nixiesearch
    - icon: /fontawesome/brands/docker
      link: https://hub.docker.com/r/nixiesearch/nixiesearch
    - icon: /fontawesome/brands/slack
      link: https://communityinviter.com/apps/nixiesearch/nixiesearch
  status:
    new: Recently added

# Page tree
nav:
  - Docs:
    - Introduction:
      - index.md
      - Quickstart: quickstart.md
    - Features:
      - Indexing:
          - features/indexing/index.md
          - Index mapping: features/indexing/mapping.md
          - Document format: features/indexing/format.md
          - Field types:
              - features/indexing/types/index.md
              - Text and numbers: features/indexing/types/basic.md
              - Images: features/indexing/types/images.md
          - REST API: features/indexing/api.md
      - Search:
          - features/search/index.md
          - Query DSL: features/search/query.md
          - Filters: features/search/filter.md
          - Facets: features/search/facet.md
          - Sorting: features/search/sort.md
          - RAG: features/search/rag.md
          - REST API: features/search/request.md
      - Autocomplete:
          - features/autocomplete/index.md
      - Deployment:
          - deployment/index.md
          - Standalone: deployment/standalone.md
          - Distributed:
              - deployment/distributed/index.md
              - Persistence:
                  - deployment/distributed/persistence/index.md
                  - S3: deployment/distributed/persistence/s3.md
                  - Local directory: deployment/distributed/persistence/local.md
                  - In-memory: deployment/distributed/persistence/inmem.md
              - Indexing:
                  - deployment/distributed/indexing/index.md
                  - Apache Kafka: deployment/distributed/indexing/kafka.md
                  - File: deployment/distributed/indexing/file.md
    - Reference:
        - Config file: reference/config.md
        - CLI options:
            - nixiesearch standalone: reference/cli/standalone.md
            - nixiesearch index: reference/cli/index.md
            - nixiesearch search: reference/cli/search.md
        - System API:
            - Metrics: reference/api/admin/metrics.md
            - Config: reference/api/admin/config.md
            - Indices: reference/api/admin/list-indices.md
            - Stats: reference/api/admin/stats.md
        - Caching: reference/cache.md
        - ML models:
            - reference/models/index.md
            - Generative: reference/models/generative.md
            - Embedding: reference/models/embedding.md
        - Language support: reference/languages.md
  - Blog: https://medium.com/nixiesearch/
  - Slack: https://communityinviter.com/apps/nixiesearch/nixiesearch
  - Contact us: https://communityinviter.com/apps/nixiesearch/nixiesearch