name: "E2E: network+indexing tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AWS_ACCESS_KEY_ID: foo
  AWS_SECRET_ACCESS_KEY: bar

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - jvm: 21
            platform: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2
          ~/.sbt
          ~/.m2
          ~/.cache
        key: ${{ runner.os }}-sbt-x3-${{ hashFiles('**/build.sbt') }}

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt-hotspot'
        java-version: ${{ matrix.jvm }}

    - name:  Run docker-compose
      run: docker compose -f .github/compose.yaml up -d

    - name: Run tests
      run: sbt -mem 5000 'testOnly --  -n "e2e-index e2e-network"'

    - name:  Stop docker-compose
      run: docker compose -f .github/compose.yaml down
