name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - jvm: 21
            platform: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - uses: actions/cache@v2
      with:
        path: ~/.sbt ~/.m2 ~/.ivy2 ~/.cache
        key: ${{ runner.os }}-build-${{ hashFiles('build.sbt') }}

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jvm }}

    - name: Run tests
      run: sbt -mem 3000 test
